# Generated by Django 4.2.4 on 2023-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacien', '0010_remove_pharmacien_date_ajout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pharmacie/images/')),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('adresse', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('clinique', 'clinique'), ('militaire', 'militaire'), ('veterinaire', 'veterinaire')], max_length=100, null=True)),
                ('gerant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacie', to='pharmacien.pharmacien')),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
            },
        ),
    ]
