# Generated by Django 4.2.4 on 2023-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
