# Generated by Django 4.2.4 on 2023-11-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_ville_departement_pharmacie_departement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ville',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='ville',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='pharmacie',
            old_name='ville',
            new_name='region',
        ),
    ]
