# Generated by Django 4.2.4 on 2023-11-12 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_rename_ville_region_rename_ville_departement_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.departement')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.commune'),
        ),
    ]
