# Generated by Django 4.2.4 on 2023-11-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0006_alter_pharmacie_commune_alter_pharmacie_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.commune'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.departement'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.region'),
        ),
    ]
