# Generated by Django 4.2.4 on 2023-11-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
        ('pharmacie', '0008_remove_departement_region_alter_pharmacie_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.commune'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.departement'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.region'),
        ),
    ]
