# Generated by Django 4.2.4 on 2023-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_alter_pharmacie_commune_alter_pharmacie_departement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
