# Generated by Django 4.2.4 on 2023-09-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commercial', models.CharField(max_length=100, null=True)),
                ('dosage', models.CharField(max_length=50, null=True)),
                ('forme_pharmaceutique', models.CharField(max_length=100, null=True)),
                ('prix', models.FloatField(null=True)),
                ('laboratoire', models.CharField(max_length=100, null=True)),
                ('numero_autorisation', models.CharField(max_length=20, null=True)),
                ('date_autorisation', models.DateTimeField(auto_now=True, null=True)),
                ('eligible', models.BooleanField(null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medicament',
                'verbose_name_plural': 'Medicaments',
            },
        ),
    ]
