# Generated by Django 4.2.4 on 2023-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='date_autorisation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
