# Generated by Django 4.2.4 on 2023-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0004_alter_medicament_date_autorisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medicament/images/'),
        ),
    ]
