# Generated by Django 4.2.4 on 2023-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hopital/images/')),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=25, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('clinique', 'clinique'), ('centre de santé', 'centre de santé'), ('poste de santé', 'poste de sante')], max_length=100, null=True)),
                ('site_web', models.CharField(blank=True, max_length=150, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Hopital',
                'verbose_name_plural': 'Hopitaux',
            },
        ),
    ]
