# Generated by Django 4.2.4 on 2023-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_position_hopital_positionnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopital',
            name='positionnement',
        ),
        migrations.AddField(
            model_name='hopital',
            name='commune',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='departements',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopital',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
