# Generated by Django 4.2.4 on 2023-10-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_remove_hopital_positionnement_hopital_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='region',
            field=models.CharField(choices=[('Dakar', 'Dakar'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaolack', 'Kaolack'), ('Kolda', 'Kolda'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('St Louis', 'St Louis'), ('Tambacounda', 'Tambacounda'), ('Thiès', 'Thiès'), ('Ziguinchor', 'Ziguinchor'), ('Kaffrine', 'Kaffrine'), ('Kédougou', 'Kédougou'), ('Sédhiou', 'Sédhiou')], max_length=150, null=True),
        ),
    ]
