# Generated by Django 4.2.4 on 2023-11-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_alter_hopital_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hopital',
            old_name='departements',
            new_name='departement',
        ),
    ]
