# Generated by Django 4.2.4 on 2023-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0006_alter_hopital_departement_alter_hopital_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.RemoveField(
            model_name='hopital',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='hopital',
            name='departement',
        ),
        migrations.AlterField(
            model_name='hopital',
            name='region',
            field=models.CharField(choices=[('dakar', 'dakar'), ('thies', 'thies')], max_length=150, null=True),
        ),
    ]
