# Generated by Django 4.2.4 on 2023-11-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0007_prestation_remove_hopital_commune_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(null=True)),
                ('ma_prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.prestation')),
                ('mon_hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital.hopital')),
            ],
            options={
                'verbose_name': 'Prise en charge',
                'verbose_name_plural': 'Prises en charge',
            },
        ),
    ]
