# Generated by Django 4.2.4 on 2023-11-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
        ('hopital', '0009_region_remove_hopital_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='region',
        ),
        migrations.AlterField(
            model_name='hopital',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.commune'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.departement'),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localisation.region'),
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
