# Generated by Django 4.2.4 on 2023-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0012_hopital_latitude_hopital_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopital',
            name='type',
            field=models.CharField(choices=[('clinique', 'clinique'), ('centre de santé public', 'centre de santé public'), ('poste de santé', 'poste de sante'), ('centre de santé privée', 'centre de santé privée')], max_length=100, null=True),
        ),
    ]
