# Generated by Django 4.2.4 on 2023-08-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('specialite', models.CharField(choices=[('Biologie', 'Biologie'), ('Pharmacologie', 'Pharmacologie'),
                                                         ('Chimie', 'Chimie')], max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pharmacien',
                'verbose_name_plural': 'Pharmaciens',
            },
        ),
    ]
