# Generated by Django 4.2.4 on 2023-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0004_alter_pharmacien_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacien',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
