# Generated by Django 4.2.4 on 2023-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0006_alter_pharmacien_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacien',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
