# Generated by Django 4.2.4 on 2023-09-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0007_alter_pharmacien_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacien',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
