# Generated by Django 4.2.4 on 2023-10-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0010_remove_pharmacien_date_ajout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacien',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
