# Generated by Django 4.2.4 on 2023-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacien', '0011_pharmacien_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacien',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
