# Generated by Django 4.2.4 on 2023-09-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medecin/images/')),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('nom', models.CharField(max_length=100, null=True)),
                ('specialite', models.CharField(choices=[('Virologie', 'Virologie'), ('Cancerologie', 'Cancerologie'), ('Pediatrie', 'Pediatrie')], max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('hopital', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Medecin',
                'verbose_name_plural': 'Medecins',
            },
        ),
    ]
