# Generated by Django 4.2.4 on 2023-10-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_remove_medecin_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
