# Generated by Django 4.2.4 on 2023-10-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
        ('medecin', '0003_medecin_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='hopital',
        ),
        migrations.AddField(
            model_name='medecin',
            name='hopitaux',
            field=models.ManyToManyField(related_name='medecins', to='hopital.hopital'),
        ),
    ]
