# Generated by Django 4.2.4 on 2023-10-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0004_remove_medecin_hopital_medecin_hopitaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('Virologie', 'Virologie'), ('Cancerologie', 'Cancerologie'), ('Pediatrie', 'Pediatrie')], max_length=150, null=True),
        ),
    ]
