# Generated by Django 4.2.4 on 2023-11-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0005_alter_medecin_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
